package common

const (
	MESSAGE_TYPE_BET uint8 = 0x01
	MESSAGE_TYPE_ACK uint8 = 0xFF
	
	ACK_OK uint8 = 0x00
	
	SIZE_MESSAGE_TYPE	int = 1
	SIZE_ACK_MESSAGE uint32 = 4
	SIZE_SERIALIZED_BET_LENGHT int = 2
	SIZE_UINT16 uint8 = 2

	AGENCY_ID_TYPE = 0x10
	CLIENT_NAME_TYPE = 0x11
	CLIENT_SURNAME_TYPE = 0x12
	CLIENT_DNI_TYPE = 0x13
	CLIENT_BIRTHDATE_TYPE = 0x14
	BET_NUMBER_TYPE = 0x15
)
