package common

const (
	MESSAGE_TYPE_BET uint8 = 0x01
	MESSAGE_TYPE_CHUNK uint8 = 0x02
	MESSAGE_TYPE_LAST_CHUNK uint8 = 0x03
	MESSAGE_TYPE_ACK uint8 = 0xFF
	MESSAGE_TYPE_LOTTERY_RESULT uint8 = 0x04
	
	ACK_OK uint8 = 0x00
	
	SIZE_MESSAGE_TYPE	int = 1
	SIZE_ACK_MESSAGE uint32 = 4
	SIZE_UINT16 int = 2

	AGENCY_ID_TYPE = 0x10
	CLIENT_NAME_TYPE = 0x11
	CLIENT_SURNAME_TYPE = 0x12
	CLIENT_DNI_TYPE = 0x13
	CLIENT_BIRTHDATE_TYPE = 0x14
	BET_NUMBER_TYPE = 0x15

	BETS_FILE_PATH = "./agency.csv"
	MAX_CHUNK_SIZE = 8192 // 8 KB
	HEADER_SIZE = SIZE_MESSAGE_TYPE + SIZE_UINT16 // 1 + 2 = 3 bytes
)
